import type { Metadata } from 'next';
import { inter, playfair } from '@/lib/fonts/fonts';
import './globals.css';

export const metadata: Metadata = {
	title: 'THE GLAM',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.variable} ${playfair.variable} antialiased`}>{children}</body>
		</html>
	);
}
